CREATE TABLE DM_FULLBOOK_CUSTOMER_NEW
(
ID INTEGER,
RID INTEGER,
R_ID INTEGER,
CUSTID VARCHAR(255),
LASTNAME VARCHAR(255),
EMAIL VARCHAR(255),
PHONENUMBER VARCHAR(255),
GUEST_CODES VARCHAR(100),
GUEST_NOTES VARCHAR(1000),
SOURCE VARCHAR(10)
);

-- GUEST CENTER

INSERT INTO DM_FULLBOOK_CUSTOMER_NEW
SELECT
ROW_NUMBER() OVER ( ORDER BY RID, CUSTID )
, RID
, R_ID
, CUSTID
, LASTNAME
, EMAIL
, PHONENUMBER
, CODES
, NOTES
FROM
(SELECT DISTINCT
 G.RID
, FERB.R_ID
, FERB.CUSTID
, G.LASTNAME
, G.EMAIL
, GP.PHONENUMBER_NUMBER AS PHONENUMBER
, GC.CODES
, G.NOTES
FROM STG_GUEST_CENTER.ADMIN.STG_GC_GUEST G
LEFT JOIN STG_GUEST_CENTER.ADMIN.STG_GC_GUEST_CODES GC
ON G.GUESTID = GC.GUESTID
LEFT JOIN STG_GUEST_CENTER.ADMIN.STG_GC_GUEST_PHONE GP
ON G.GUESTID = GP.GUESTID
JOIN ANALYTICS_DW..FCT_ERBRESERVATION FERB
ON G.RID = FERB.RID
AND G.GUESTID = FERB.CUSTID) A;

-- ERB

INSERT INTO DM_FULLBOOK_CUSTOMER_NEW
SELECT
ROW_NUMBER() OVER ( ORDER BY RID, CUSTID ) + 5435020
, RID
, R_ID
, CUSTID
, LASTNAME
, EMAIL
, PHONENUMBER
, CODES
, NOTES
, 'ERB'
FROM
(SELECT DISTINCT
 EC.RID
, FERB.R_ID
, FERB.CUSTID
, EC.LNAME AS LASTNAME
, EC.EMAIL
, ECP.PHONE AS PHONENUMBER
, ECC.CCODE AS CODES
, EC.NOTES
FROM STG_ERB.ADMIN.ERBCUSTOMER EC
LEFT JOIN STG_ERB.ADMIN.ERBCUSTOMERCODE ECC
ON EC.RID = ECC.RID
LEFT JOIN STG_ERB.ADMIN.ERBCUSTOMERPHONE ECP
ON EC.RID = ECP.RID
AND EC.CUSTID = ECP.CUSTID
JOIN ANALYTICS_DW..FCT_ERBRESERVATION FERB
ON EC.RID = FERB.RID
AND EC.CUSTID = FERB.CUSTID
WHERE FERB.SOURCE = 'ERB') A;