set enable_factrel_planner=1;

INSERT INTO FCT_ERBRESERVATION
SELECT 
ERBRESERVATIONID,
STERB.RID,
DMR.R_ID,
STERB.RESID,
CALLERID,
CALLERCOMPANYID,
CUSTID,
RESTIME,
PARTYSIZE,
FINALSLOTSIZEMIN,
FINALSLOTSIZEMAX,
RSTATEID,
DATEMADE,
TIMEARRIVED,
TIMESEATED,
TIMECOMPLETED,
TIMESTATECHANGED,
SEATEDSIZE,
CUSTPHONETYPEID,
CALLERPHONETYPEID,
ISARCHIVED,
ISSLOTARCHIVED,
SHIFTDATE,
SHIFTID,
TABLENAME,
ISWALKIN,
WALKINFNAME,
WALKINLNAME,
USERID,
CONFNUMBER,
WEBCONFNUMBER,
WANTSCONFIRMATION,
CONFIRMATIONSENT,
NOTES,
RESTYPEID,
SHARESTATUSID,
MODIFIEDBY,
MODIFIEDTERMINALID,
MODIFIEDDATE,
RESTURNTIME,
PREASSIGNLOCKED,
PACINGLIMIT,
FORCEFLAGS,
RECURRINGGROUPID,
0 as ERBTS,
RESSOURCEID,
case when ERBCCR.RESID is not null then 1 else 0 end as CCRequired,
'ERB' as source,
case  
when (EXTRACT(MINUTE FROM TIMEARRIVED) between 45 and 59) and (EXTRACT(HOUR FROM TIMEARRIVED) <23)
then EXTRACT(HOUR FROM TIMEARRIVED)+1
when  (EXTRACT(MINUTE FROM TIMEARRIVED) between 45 and 59) and (EXTRACT(HOUR FROM TIMEARRIVED) =23) then '00'
else EXTRACT(HOUR FROM TIMEARRIVED) end
||':'||case when EXTRACT(MINUTE FROM TIMEARRIVED) between 00 and 14 then '00'
     when EXTRACT(MINUTE FROM TIMEARRIVED) between 15 and 44 then '30'
	 when (EXTRACT(MINUTE FROM TIMEARRIVED) between 45 and 59) then '00' end  timearrived_30,
	 
case 
when (EXTRACT(MINUTE FROM TIMESEATED) between 45 and 59) and (EXTRACT(HOUR FROM TIMESEATED) <23) then EXTRACT(HOUR FROM TIMESEATED)+1 
when  (EXTRACT(MINUTE FROM TIMESEATED) between 45 and 59) and (EXTRACT(HOUR FROM TIMESEATED) =23) then '00'
 else EXTRACT(HOUR FROM TIMESEATED) end 
	   ||':'|| case when EXTRACT(MINUTE FROM TIMESEATED) between 00 and 14 then '00'
     when EXTRACT(MINUTE FROM TIMESEATED) between 15 and 44 then '30'
	 when (EXTRACT(MINUTE FROM TIMESEATED) between 45 and 59) then '00' end timeseated_30 			
FROM STG_ERB..ERBRESERVATION STERB
LEFT JOIN ANALYTICS_DW..DM_RESTAURANT DMR ON STERB.RID=DMR.RID
left join STG_ERB..ERBCREDITCARDRESERVATIONS ERBCCR on STERB.RID=ERBCCR.RID and STERB.RESID=ERBCCR.RESID;

INSERT INTO FCT_ERBRESERVATION
SELECT A.RESERVATIONID ERBRESERVATIONID
       , A.RID
       , R.R_ID
       , -1 RESID
       , NULL CALLERID
       , NULL CALLERCOMPANYID
       , A.GUESTID CUSTID
       , TIMESTAMP('1900-01-01 ' || SUBSTRING(A.SCHEDULED, 12, 5)) RESTIME
       , A.PARTYSIZE
       , NULL FINALSLOTSIZEMIN
       , NULL FINALSLOTSIZEMAX 
       , CASE WHEN A.STATE = 'AllArrived' THEN 1
			  WHEN A.STATE IN ('Seated','AssumedDone') THEN 2
			  WHEN A.STATE IN ('Done') THEN 3 	
			  WHEN A.STATE = 'NoShow' THEN 4	
			  WHEN A.STATE = 'Cancelled' THEN 5 	
			  WHEN A.STATE = 'Confirmed' THEN 6
			  WHEN A.STATE = 'Dessert' THEN 7	
			  WHEN A.STATE = 'NotConfirmed' THEN 8	
			  WHEN A.STATE = 'PartiallySeated' THEN 13
			  WHEN A.STATE = 'Paid' THEN 15
			  WHEN A.STATE = 'Entree' THEN 17
			  WHEN A.STATE = 'CheckDropped' THEN 18
			  WHEN A.STATE = 'AssumedSeated' THEN 23
			ELSE -1 END RSTATEID 
       , CASE WHEN A.CREATED IS NULL THEN '1900-01-01' ELSE A.CREATED END DATEMADE  
       , A.ARRIVED TIMEARRIVED
       , A.SEATED TIMESEATED
       , A.COMPLETED TIMECOMPLETED
       , NULL TIMESTATECHANGED
       , NULL SEATEDSIZE
       , NULL CUSTPHONETYPEID
       , NULL CALLERPHONETYPEID
       , NULL ISARCHIVED
       , NULL ISSLOTARCHIVED
       , DATE_TRUNC('DAY',SCHEDULED) SHIFTDATE
       , NULL SHIFTID
       , NULL TABLENAME
       , CASE WHEN A.ORIGIN = 'WALKIN' THEN 1 ELSE 0 END ISWALKIN
       , NULL WALKINFNAME
       , NULL WALKINLNAME
       , NULL USERID
       , A.CONFIRMATIONNUMBER CONFNUMBER
       , NULL WEBCONFNUMBER
       , NULL WANTSCONFIRMATION
       , NULL CONFIRMATIONSENT
       , A.VENUENOTES NOTES
       , NULL RESTYPEID
       , NULL SHARESTATUSID
       , NULL MODIFIEDBY
       , NULL MODIFIEDTERMINALID
       , NULL MODIFIEDDATE
       , NULL RESTURNTIME
       , NULL PREASSIGNLOCKED
       , NULL PACINGLIMIT
       , NULL FORCEFLAGS
       , NULL RECURRINGGROUPID
       , NULL ERBTS
       , CASE WHEN A.ORIGIN = 'WEB' THEN 2 WHEN A.ORIGIN = 'PHONE' THEN 1 WHEN A.ORIGIN = 'WALKIN' THEN 3 ELSE -1 END RESSOURCEID  
       , NULL CCREQUIRED 
	   , 'GC' AS SOURCE,
	   	case  when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59)  and (EXTRACT(HOUR FROM A.ARRIVED) < 23)  then EXTRACT(HOUR FROM A.ARRIVED)+1 
			   when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59)  and (EXTRACT(HOUR FROM A.ARRIVED) = 23)   then '00' 
			   else EXTRACT(HOUR FROM A.ARRIVED) end
			   ||':'||case when EXTRACT(MINUTE FROM A.ARRIVED) between 00 and 14 then '00'
			        when EXTRACT(MINUTE FROM A.ARRIVED) between 15 and 44 then '30'
			   	 when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59) then '00' end  timearrived_30,
			   	 
			    case when (EXTRACT(MINUTE FROM a.SEATED) between 45 and 59) and (EXTRACT(HOUR FROM A.SEATED) < 23) 	 then EXTRACT(HOUR FROM  a.SEATED)+1 
			    when (EXTRACT(MINUTE FROM A.SEATED) between 45 and 59)  and (EXTRACT(HOUR FROM A.SEATED) = 23)  then '00' 
			    else EXTRACT(HOUR FROM  a.SEATED) end 
			   	   ||':'|| case when EXTRACT(MINUTE FROM  a.SEATED) between 00 and 14 then '00'
			        when EXTRACT(MINUTE FROM  a.SEATED) between 15 and 44 then '30'
	 when (EXTRACT(MINUTE FROM  a.SEATED) between 45 and 59) then '00' end  timeseated_30
  FROM STG_GUEST_CENTER.ADMIN.STG_GC_RESERVATION A
  	   JOIN ANALYTICS_DW..DM_RESTAURANT R ON R.RID = A.RID  
WHERE INSTR(A.RESERVATIONID, '_' || A.RID || '_') = 0;

INSERT INTO FCT_ERBRESERVATION
SELECT A.RESERVATIONID ERBRESERVATIONID
       , A.RID
       , R.R_ID
       , -1 RESID
       , NULL CALLERID
       , NULL CALLERCOMPANYID
       , A.GUESTID CUSTID
       , TIMESTAMP('1900-01-01 ' || SUBSTRING(A.SCHEDULED, 12, 5)) RESTIME
       , A.PARTYSIZE
       , NULL FINALSLOTSIZEMIN
       , NULL FINALSLOTSIZEMAX 
       , CASE WHEN A.STATE = 'AllArrived' THEN 1
			  WHEN A.STATE IN ('Seated','AssumedDone') THEN 2
			  WHEN A.STATE IN ('Done') THEN 3 	
			  WHEN A.STATE = 'NoShow' THEN 4	
			  WHEN A.STATE = 'Cancelled' THEN 5 	
			  WHEN A.STATE = 'Confirmed' THEN 6
			  WHEN A.STATE = 'Dessert' THEN 7	
			  WHEN A.STATE = 'NotConfirmed' THEN 8	
			  WHEN A.STATE = 'PartiallySeated' THEN 13
			  WHEN A.STATE = 'Paid' THEN 15
			  WHEN A.STATE = 'Entree' THEN 17
			  WHEN A.STATE = 'CheckDropped' THEN 18
			  WHEN A.STATE = 'AssumedSeated' THEN 23
			ELSE -1 END RSTATEID 
       , CASE WHEN A.CREATED IS NULL THEN '1900-01-01' ELSE A.CREATED END DATEMADE 
       , A.ARRIVED TIMEARRIVED
       , A.SEATED TIMESEATED
       , A.COMPLETED TIMECOMPLETED
       , NULL TIMESTATECHANGED
       , NULL SEATEDSIZE
       , NULL CUSTPHONETYPEID
       , NULL CALLERPHONETYPEID
       , NULL ISARCHIVED
       , NULL ISSLOTARCHIVED
       , DATE_TRUNC('DAY',SCHEDULED) SHIFTDATE
       , NULL SHIFTID
       , NULL TABLENAME
       , CASE WHEN A.ORIGIN = 'WALKIN' THEN 1 ELSE 0 END ISWALKIN
       , NULL WALKINFNAME
       , NULL WALKINLNAME
       , NULL USERID
       , A.CONFIRMATIONNUMBER CONFNUMBER
       , NULL WEBCONFNUMBER
       , NULL WANTSCONFIRMATION
       , NULL CONFIRMATIONSENT
       , A.VENUENOTES NOTES
       , NULL RESTYPEID
       , NULL SHARESTATUSID
       , NULL MODIFIEDBY
       , NULL MODIFIEDTERMINALID
       , NULL MODIFIEDDATE
       , NULL RESTURNTIME
       , NULL PREASSIGNLOCKED
       , NULL PACINGLIMIT
       , NULL FORCEFLAGS
       , NULL RECURRINGGROUPID
       , NULL ERBTS
       , CASE WHEN A.ORIGIN = 'WEB' THEN 2 WHEN A.ORIGIN = 'PHONE' THEN 1 WHEN A.ORIGIN = 'WALKIN' THEN 3 ELSE -1 END RESSOURCEID  
       , NULL CCREQUIRED 
	   , 'GC' AS SOURCE,
	   	   case  when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59)  and (EXTRACT(HOUR FROM A.ARRIVED) < 23)  then EXTRACT(HOUR FROM A.ARRIVED)+1 
		   			   when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59)  and (EXTRACT(HOUR FROM A.ARRIVED) = 23)   then '00' 
		   			   else EXTRACT(HOUR FROM A.ARRIVED) end
		   			   ||':'||case when EXTRACT(MINUTE FROM A.ARRIVED) between 00 and 14 then '00'
		   			        when EXTRACT(MINUTE FROM A.ARRIVED) between 15 and 44 then '30'
		   			   	 when (EXTRACT(MINUTE FROM A.ARRIVED) between 45 and 59) then '00' end  timearrived_30,
		   			   	 
		   			    case when (EXTRACT(MINUTE FROM a.SEATED) between 45 and 59) and (EXTRACT(HOUR FROM A.SEATED) < 23) 	 then EXTRACT(HOUR FROM  a.SEATED)+1 
		   			    when (EXTRACT(MINUTE FROM A.SEATED) between 45 and 59)  and (EXTRACT(HOUR FROM A.SEATED) = 23)  then '00' 
		   			    else EXTRACT(HOUR FROM  a.SEATED) end 
		   			   	   ||':'|| case when EXTRACT(MINUTE FROM  a.SEATED) between 00 and 14 then '00'
		   			        when EXTRACT(MINUTE FROM  a.SEATED) between 15 and 44 then '30'
	 when (EXTRACT(MINUTE FROM  a.SEATED) between 45 and 59) then '00' end  timeseated_30
  FROM STG_GUEST_CENTER..STG_GC_RESERVATION A
  	   JOIN ANALYTICS_DW..DM_RESTAURANT R ON R.RID = A.RID 
	   LEFT JOIN ANALYTICS_DW..FCT_ERBRESERVATION E ON E.RID = A.RID AND DATE_TRUNC('MONTH', E.SHIFTDATE) = DATE_TRUNC('MONTH', A.SCHEDULED)
WHERE A.RESERVATIONID LIKE 'ERB_%'
AND E.RID IS NULL AND DATE_TRUNC('MONTH', E.SHIFTDATE) IS NULL;

