SELECT
 	date(now()) date_stamp,
    sum(case when B.USERID IS NULL AND B.DB_NAME IS NULL then 1 else 0 end) new_users,
	sum(case when nvl(a.EMAIL,'') <> nvl(b.EMAIL,'') then 1 else 0 end) EMAIL, 
	sum(case when nvl(a.FIRSTNAME,'') <> nvl(b.FIRSTNAME,'') then 1 else 0 end) FIRSTNAME,
	sum(case when nvl(a.LASTNAME,'') <> nvl(b.LASTNAME,'') then 1 else 0 end) LASTNAME, 
	sum(case when nvl(a.METROAREAID,-1) <> nvl(b.METROAREAID,-1) then 1 else 0 end) METROAREAID, 
	sum(case when nvl(A.USERTYPE,'') <> nvl(B.USERTYPE,'') then 1 else 0 end) USERTYPE,
    sum(case when nvl(A.CONSUMERTYPE,'') <> nvl(B.CONSUMERTYPE,'') then 1 else 0 end) CONSUMERTYPE,
	sum(case when a.STATUS <> b.STATUS then 1 else 0 end) STATUS, 
	sum(case when nvl(a.REGISTRATIONDATE,'1900-01-01') <> nvl(b.REGISTRATIONDATE,'1900-01-01') then 1 else 0 end) REGISTRATIONDATE,
	sum(case when a.OPTINSTATUS <> b.OPTINSTATUS then 1 else 0 end) OPTINSTATUS, 
	sum(case when a.INSIDERNEWSSTATUS <> b.INSIDERNEWSSTATUS then 1 else 0 end) INSIDERNEWSSTATUS, 
	sum(case when a.DINERSCHOICESTATUS <> b.DINERSCHOICESTATUS then 1 else 0 end) DINERSCHOICESTATUS,
	sum(case when a.NEWHOTSTATUS <> b.NEWHOTSTATUS then 1 else 0 end) NEWHOTSTATUS, 
	sum(case when a.RESTAURANTWEEKSTATUS <> b.RESTAURANTWEEKSTATUS then 1 else 0 end) RESTAURANTWEEKSTATUS, 
	sum(case when a.PROMOTIONALSTATUS <> b.PROMOTIONALSTATUS then 1 else 0 end) PROMOTIONALSTATUS, 
	sum(case when a.PRODUCTSTATUS <> b.PRODUCTSTATUS then 1 else 0 end) PRODUCTSTATUS, 
	sum(case when a.PLACESIVEEATEN_YN <> b.PLACESIVEEATEN_YN then 1 else 0 end) PLACESIVEEATEN_YN, 
	sum(case when a.GOOGLESIGNIN_YN <> b.GOOGLESIGNIN_YN then 1 else 0 end) GOOGLESIGNIN_YN, 
	sum(case when a.FBSIGNIN_YN <> b.FBSIGNIN_YN then 1 else 0 end) FBSIGNIN_YN,
	sum(case when nvl(a.LIFETIME_RESOS,0) <> nvl(b.LIFETIME_RESOS,0) then 1 else 0 end) LIFETIME_RESOS, 
    sum(case when nvl(a.LASTRESOSEATEDDATE, '1900-01-01') <> nvl(b.LASTRESOSEATEDDATE, '1900-01-01') then 1 else 0 end) LASTRESOSEATEDDATE,
	sum(case when nvl(a.LASTRID,0) <> nvl(b.LASTRID,0) then 1 else 0 end) LASTRID, 
   	sum(case when nvl(a.LASTRNAME,'') <> nvl(b.LASTRNAME,'') then 1 else 0 end) LASTRNAME, 
	sum(case when nvl(a.LASTREFERRERID,0) <> nvl(b.LASTREFERRERID,0) then 1 else 0 end) LASTREFERRERID, 
    sum(case when nvl(a.LASTBILLINGTYPE,'') <> nvl(b.LASTBILLINGTYPE,'') then 1 else 0 end) LASTBILLINGTYPE, 
	sum(case when nvl(a.LASTPARTNERID,0) <> nvl(b.LASTPARTNERID,0) then 1 else 0 end) LASTPARTNERID, 
	sum(case when nvl(a.FIRSTRESOSEATEDDATE, '1900-01-01') <> nvl(b.FIRSTRESOSEATEDDATE, '1900-01-01') then 1 else 0 end) FIRSTRESOSEATEDDATE, 
	sum(case when nvl(a.FIRSTBILLINGTYPE,'') <> nvl(b.FIRSTBILLINGTYPE,'') then 1 else 0 end) FIRSTBILLINGTYPE,
	sum(case when nvl(a.FIRSTPARTNERID,0) <> nvl(b.FIRSTPARTNERID,0) then 1 else 0 end) FIRSTPARTNERID, 
	sum(case when nvl(a.MINAPPRESOSEATEDDATE, '1900-01-01') <> nvl(b.MINAPPRESOSEATEDDATE , '1900-01-01') then 1 else 0 end) MINAPPRESOSEATEDDATE, 
	sum(case when nvl(a.NEXTRESODATE, '1900-01-01') <> nvl(b.NEXTRESODATE, '1900-01-01') then 1 else 0 end) NEXTRESODATE, 
	sum(case when nvl(a.TOTALSEATEDRESO,0) <> nvl(b.TOTALSEATEDRESO,0) then 1 else 0 end) TOTALSEATEDRESO, 
	sum(case when nvl(a.MOBILEWEBRESO,0) <> nvl(b.MOBILEWEBRESO,0) then 1 else 0 end) MOBILEWEBRESO,
	sum(case when nvl(a.IPHONERESO,0) <> nvl(b.IPHONERESO,0) then 1 else 0 end) IPHONERESO, 
	sum(case when nvl(a.IPADRESO,0) <> nvl(b.IPADRESO,0) then 1 else 0 end) IPADRESO, 
	sum(case when nvl(a.ANDROIDRESO,0) <> nvl(b.ANDROIDRESO,0) then 1 else 0 end) ANDROIDRESO, 
	sum(case when nvl(a.POPRESO,0) <> nvl(b.POPRESO,0) then 1 else 0 end) POPRESO, 
	sum(case when nvl(a.RWRESO,0) <> nvl(b.RWRESO,0) then 1 else 0 end) RWRESO,
	sum(case when nvl(a.TRAVELLERMETRO,0) <> nvl(b.TRAVELLERMETRO,0) then 1 else 0 end) TRAVELLERMETRO, 
	sum(case when nvl(a.LIFETIMEPTSEARNED,0) <> nvl(b.LIFETIMEPTSEARNED,0) then 1 else 0 end) LIFETIMEPTSEARNED, 
	sum(case when nvl(a.TOTALREDEEMABLEPTS,0) <> nvl(b.TOTALREDEEMABLEPTS,0) then 1 else 0 end) TOTALREDEEMABLEPTS, 
	sum(case when nvl(a.TOTALREWARDREDEMPTIONS,0) <> nvl(b.TOTALREWARDREDEMPTIONS,0) then 1 else 0 end) TOTALREWARDREDEMPTIONS,
	sum(case when nvl(a.LASTREDEMPTION_DATE, '1900-01-01') <> nvl(b.LASTREDEMPTION_DATE, '1900-01-01') then 1 else 0 end) LASTREDEMPTION_DATE,
	sum(case when nvl(a.SS_RESTAURANTEMAILOPTIN,0) <> nvl(b.SS_RESTAURANTEMAILOPTIN,0) then 1 else 0 end) SS_RESTAURANTEMAILOPTIN, 
	sum(case when nvl(a.SS_TWOORMOREGID,0) <> nvl(b.SS_TWOORMOREGID,0) then 1 else 0 end) SS_TWOORMOREGID,
	sum(case when nvl(a.SS_TWOORMOREREVIEW,0) <> nvl(b.SS_TWOORMOREREVIEW,0) then 1 else 0 end) SS_TWOORMOREREVIEW , 
	sum(case when nvl(a.FIRSTBILLINGRID,0) <> nvl(b.FIRSTBILLINGRID,0) then 1 else 0 end) FIRSTBILLINGRID, 
	sum(case when nvl(a.LASTSEATEDREVIEWED_YN,0) <> nvl(b.LASTSEATEDREVIEWED_YN,0) then 1 else 0 end) LASTSEATEDREVIEWED_YN,
	sum(case when nvl(a.REGIONID,-1) <> nvl(b.REGIONID,-1) then 1 else 0 end)  REGIONID, 
	sum(case when nvl(a.REGIONID2,-1) <> nvl(b.REGIONID2,-1) then 1 else 0 end)  REGIONID2,
	sum(case when nvl(a.PAYMENT_ENABLED_FLAG,0) <> nvl(b.PAYMENT_ENABLED_FLAG,0) then 1 else 0 end) PAYMENT_ENABLED_FLAG,
	sum(case when nvl(a.PAYMENT_ENABLED_DATESTAMP, '1900-01-01') <> nvl(b.PAYMENT_ENABLED_DATESTAMP, '1900-01-01') then 1 else 0 end) PAYMENT_ENABLED_DATESTAMP,
	sum(case when nvl(a.LAST_PAID_RID,0) <> nvl(b.LAST_PAID_RID,0) then 1 else 0 end) LAST_PAID_RID,
	sum(case when nvl(a.LAST_PAID_SHIFTDATE, '1900-01-01') <> nvl(b.LAST_PAID_SHIFTDATE, '1900-01-01') then 1 else 0 end) LAST_PAID_SHIFTDATE, 
	sum(case when nvl(a.PAYMENT_USAGE_YR,0) <> nvl(b.PAYMENT_USAGE_YR,0) then 1 else 0 end) PAYMENT_USAGE_YR
 from
	STG_SILVERPOP_USERS_MASTER_ALL a
	left join STG_SILVERPOP_USERS_MASTER_ALL_BKP_PREVDAY  b on b.userid = a.userid and b.db_name = a.db_name group by
  date(now())