-- ***************************

SELECT
COUNTRY
, REPORTING_SUITE
, SUM(RR_TOTAL) AS RR_TOTAL
, SUM(STD_TOTAL) AS STD_TOTAL
, SUM(RR_FULL_WEB) AS RR_FULL_WEB
, SUM(RR_MOB_WEB) AS RR_MOB_WEB
, SUM(STD_FULL_WEB) AS STD_FULL_WEB
, SUM(STD_MOB_WEB) AS STD_MOB_WEB
, SUM(IPHONE) AS IPHONE
, SUM(IPAD) AS IPAD
, SUM(ANDROID) AS ANDROID
FROM (SELECT FCR.COUNTRY
, CASE --WHEN FCR.BILLINGTYPE = 'RestRefReso' THEN 'RR_TOTAL'
		    --WHEN FCR.BILLINGTYPE <> 'RestRefReso' THEN 'STD_TOTAL'
			WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'RR_FULL_WEB'
			WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'RR_MOB_WEB'
			WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'STD_FULL_WEB'
			WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'STD_MOB_WEB'
			WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN 'IPHONE'
			WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN 'IPAD'
			WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN 'ANDROID'
		ELSE NULL END AS REPORTING_SUITE			
, 0 RR_TOTAL
, 0 STD_TOTAL
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID ELSE NULL END) RR_FULL_WEB
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN RES_ID ELSE NULL END) RR_MOB_WEB
, COUNT(CASE WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID ELSE NULL END) STD_FULL_WEB
, COUNT(CASE WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN RES_ID ELSE NULL END) STD_MOB_WEB
, COUNT(CASE WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN RES_ID ELSE NULL END) IPHONE
--, CASE WHEN FCR.PARTNERID IN (1007) THEN COUNT(RES_ID) ELSE NULL END NEW_IPHONE
, COUNT(CASE WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN RES_ID ELSE NULL END) IPAD
--, CASE WHEN FCR.PARTNERID IN (1010) THEN COUNT(RES_ID) ELSE NULL END NEW_IPAD
, COUNT(CASE WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN RES_ID ELSE NULL END) ANDROID
--, CASE WHEN FCR.PARTNERID IN (1663) THEN COUNT(RES_ID) ELSE NULL END NEW_ANDROID
	 
FROM FCT_RESERVATION FCR
GROUP BY 1, 2

UNION

SELECT FCR.COUNTRY
, CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' THEN 'RR_TOTAL'
		    WHEN FCR.BILLINGTYPE <> 'RestRefReso' THEN 'STD_TOTAL'
	   ELSE NULL END AS REPORTING_SUITE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' THEN RES_ID ELSE NULL END) RR_TOTAL
, COUNT(CASE WHEN FCR.BILLINGTYPE <> 'RestRefReso' THEN RES_ID ELSE NULL END) STD_TOTAL
, 0 RR_FULL_WEB
, 0 RR_MOB_WEB
, 0 STD_FULL_WEB
, 0 STD_MOB_WEB
, 0 IPHONE
--, CASE WHEN FCR.PARTNERID IN (1007) THEN COUNT(RES_ID) ELSE NULL END NEW_IPHONE
, 0 IPAD
--, CASE WHEN FCR.PARTNERID IN (1010) THEN COUNT(RES_ID) ELSE NULL END NEW_IPAD
, 0 ANDROID
--, CASE WHEN FCR.PARTNERID IN (1663) THEN COUNT(RES_ID) ELSE NULL END NEW_ANDROID
FROM FCT_RESERVATION FCR
GROUP BY 1, 2) AA
WHERE REPORTING_SUITE IS NOT NULL
GROUP BY 1, 2;

-- ***************************

SELECT FCR.COUNTRY
, CASE 		WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'RR_FULL_WEB'
			WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'toptablemobilerestref'
			WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'STD_FULL_WEB'
			WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'toptablemobile'
			WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN 'toptableiphone'
			WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN 'toptableipad'
			WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN 'toptableandroid'
		ELSE NULL END AS REPORTING_SUITE
, SHIFTDATE
, DATEMADE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID 
			 WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN RES_IDDATESTAMP, 
			 WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN RES_ID
			 ELSE NULL END) RESOS
	 
FROM FCT_RESERVATION FCR
WHERE REPORTING_SUITE IS NOT NULL
GROUP BY 1, 2

UNION

SELECT FCR.COUNTRY
, CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' THEN 'toptablerestref'
		    WHEN FCR.BILLINGTYPE <> 'RestRefReso' THEN 'toptable'
	   ELSE NULL END AS REPORTING_SUITE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' THEN RES_ID 
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' THEN RES_ID
			 ELSE NULL END) AS RESOS
, SHIFTDATE
, DATEMADE
FROM FCT_RESERVATION FCR
WHERE REPORTING_SUITE IS NOT NULL
GROUP BY 1, 2

-- ***************************

SELECT FOMN.DATESTAMP
, FOMN.REPORTING_SUITE
, FOMN.SORT_ORDER
, FOMN.REPORT_DISPLAY
, FOMN.REPORT_ROLLUP
, CASE WHEN TRIM(FOMN.REPORTING_SUITE) IN ('toptable', 'toptableandroid', 'toptableipad', 'toptableiphone', 'toptablemobile', 'toptablemobilerestref', 'toptablerestref') THEN 'UK'
  ELSE 'DE' END COUNTRY
, SUM(FOMN.VISITS_SEARCHES) AS VISITS_SEARCHES
, SUM(FOMN.VISITS) AS VISITS
, SUM(FOMN.SEARCHES_SERIALIZED) AS SEARCHES_SERIALIZED
, SUM(FOMN.NEW_RESERVATIONS_SERIALIZED) AS NEW_RESERVATIONS_SERIALIZED
, SUM(FOMN.SEO_VISITS) AS SEO_VISITS
, SUM(FRES.RESOS) AS RESOS

FROM FCT_OMNITURE FOMN
JOIN 
(SELECT
 CASE 		WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'toptablerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'toptablemobilerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'toptable'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'toptablemobile'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1345, 1007, 84) THEN 'toptableiphone'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1010, 1467, 183) THEN 'toptableipad'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1468, 123, 1663) THEN 'toptableandroid'
			
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'europerestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'demobilewebrestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'oteurope'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'demobileweb'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1345, 1007, 84) THEN 'otdeiphone'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1010, 1467, 183) THEN 'otdeipad'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1468, 123, 1663) THEN 'otdeandroid'
		ELSE NULL END AS REPORTING_SUITE
, DATE(DATEMADE) DATEMADE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID 
			 WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN RES_ID 
			 WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN RES_ID
			 ELSE NULL END) RESOS
	 
FROM FCT_RESERVATION FCR
WHERE REPORTING_SUITE IS NOT NULL
AND COUNTRY IN ('UK', 'IE', 'DE')
GROUP BY 1, 2) FRES
ON FOMN.DATESTAMP = DATE(FRES.DATEMADE)
AND FOMN.REPORTING_SUITE = FRES.REPORTING_SUITE
WHERE FOMN.DATESTAMP = '2015-05-03'
GROUP BY 1, 2, 3, 4, 5, 6

-- ***************************

DROP VIEW VW_RES_BOOKED_TRAFFIC;

CREATE OR REPLACE VIEW VW_RES_BOOKED_TRAFFIC
AS
SELECT FOMN.DATESTAMP AS DATE_STAMP
, FOMN.REPORTING_SUITE
, FOMN.SORT_ORDER
, FOMN.REPORT_DISPLAY
, FOMN.REPORT_ROLLUP
, CASE WHEN TRIM(FOMN.REPORTING_SUITE) IN ('toptable', 'toptableandroid', 'toptableipad', 'toptableiphone', 'toptablemobile', 'toptablemobilerestref', 'toptablerestref') THEN 'UK'
  ELSE 'DE' END COUNTRYID
, SUM(FOMN.VISITS_SEARCHES) AS VISITS_SEARCHES
, SUM(FOMN.VISITS) AS VISITS
, SUM(FOMN.SEARCHES_SERIALIZED) AS SEARCHES_SERIALIZED
, SUM(FOMN.NEW_RESERVATIONS_SERIALIZED) AS NEW_RESERVATIONS_SERIALIZED
, SUM(FOMN.SEO_VISITS) AS SEO_VISITS
, SUM(FRES.RESOS) AS RESOS

FROM FCT_OMNITURE FOMN
JOIN 
(SELECT
 CASE 		WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'toptablerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'toptablemobilerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'toptable'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'toptablemobile'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1345, 1007, 84) THEN 'toptableiphone'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1010, 1467, 183) THEN 'toptableipad'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.PARTNERID IN (1468, 123, 1663) THEN 'toptableandroid'
			
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'europerestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN 'demobilewebrestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN 'oteurope'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN 'demobileweb'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1345, 1007, 84) THEN 'otdeiphone'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1010, 1467, 183) THEN 'otdeipad'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.PARTNERID IN (1468, 123, 1663) THEN 'otdeandroid'
		ELSE NULL END AS REPORTING_SUITE
, DATE(DATEMADE) DATEMADE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID 
			 WHEN FCR.BILLINGTYPE = 'RestRefReso' AND FCR.PARTNERID IN (1043, 291) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1, 1101, 252, 249) THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND FCR.PARTNERID IN (1043, 291, 1348) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1345, 1007, 84) THEN RES_ID 
			 WHEN FCR.PARTNERID IN (1010, 1467, 183) THEN RES_ID
			 WHEN FCR.PARTNERID IN (1468, 123, 1663) THEN RES_ID
			 ELSE NULL END) RESOS
	 
FROM FCT_RESERVATION FCR
WHERE REPORTING_SUITE IS NOT NULL
AND COUNTRY IN ('UK', 'IE', 'DE')
GROUP BY 1, 2) FRES
ON FOMN.DATESTAMP = DATE(FRES.DATEMADE)
AND FOMN.REPORTING_SUITE = FRES.REPORTING_SUITE
--WHERE FOMN.DATESTAMP = '2015-05-03'
GROUP BY 1, 2, 3, 4, 5, 6;

-- ***************************

CREATE OR REPLACE VIEW VW_RES_BOOKED_TRAFFIC
AS
SELECT FOMN.DATESTAMP AS DATE_STAMP
, FOMN.REPORTING_SUITE
, FOMN.SORT_ORDER
, FOMN.REPORT_DISPLAY
, FOMN.REPORT_ROLLUP
, CASE WHEN TRIM(FOMN.REPORTING_SUITE) IN ('toptable', 'toptableandroid', 'toptableipad', 'toptableiphone', 'toptablemobile', 'toptablemobilerestref', 'toptablerestref') THEN 'UK'
  ELSE 'DE' END COUNTRYID
, SUM(FOMN.VISITS_SEARCHES) AS VISITS_SEARCHES
, SUM(FOMN.VISITS) AS VISITS
, SUM(FOMN.SEARCHES_SERIALIZED) AS SEARCHES_SERIALIZED
, SUM(FOMN.NEW_RESERVATIONS_SERIALIZED) AS NEW_RESERVATIONS_SERIALIZED
, SUM(FOMN.SEO_VISITS) AS SEO_VISITS
, SUM(FRES.RESOS) AS RESOS

FROM FCT_OMNITURE FOMN
JOIN 
(SELECT
  CASE 		WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN 'toptablerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN 'toptablemobilerestref'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN 'toptable'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN 'toptablemobile'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND DPA.PLATFORM = 'IPHONE' THEN 'toptableiphone'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND DPA.PLATFORM = 'IPAD' THEN 'toptableipad'
			WHEN FCR.COUNTRY IN ('UK', 'IE') AND DPA.PLATFORM = 'ANDROID' THEN 'toptableandroid'
			
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN 'europerestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN 'demobilewebrestref'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN 'oteurope'
			WHEN FCR.COUNTRY IN ('DE') AND FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN 'demobileweb'
			WHEN FCR.COUNTRY IN ('DE') AND DPA.PLATFORM = 'IPHONE' THEN 'otdeiphone'
			WHEN FCR.COUNTRY IN ('DE') AND DPA.PLATFORM = 'IPAD' THEN 'otdeipad'
			WHEN FCR.COUNTRY IN ('DE') AND DPA.PLATFORM = 'ANDROID' THEN 'otdeandroid'
		ELSE NULL END AS REPORTING_SUITE
, DATE(DATEMADE) DATEMADE
, COUNT(CASE WHEN FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN RES_ID 
			 WHEN FCR.BILLINGTYPE = 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'PC' THEN RES_ID
			 WHEN FCR.BILLINGTYPE <> 'RestRefReso' AND DPA.PLATFORM = 'MOBILE WEB' THEN RES_ID
			 WHEN DPA.PLATFORM = 'IPHONE' THEN RES_ID 
			 WHEN DPA.PLATFORM = 'IPAD' THEN RES_ID
			 WHEN DPA.PLATFORM = 'ANDROID' THEN RES_ID
			 ELSE NULL END) RESOS
	 
FROM FCT_RESERVATION FCR
JOIN DM_PARTNER_APPLICATION DPA
ON FCR.PARTNERID = DPA.PARTNERID
AND FCR.DB_NAME = DPA.DB_NAME
WHERE REPORTING_SUITE IS NOT NULL
AND COUNTRY IN ('UK', 'IE', 'DE')
GROUP BY 1, 2) FRES
ON FOMN.DATESTAMP = DATE(FRES.DATEMADE)
AND FOMN.REPORTING_SUITE = FRES.REPORTING_SUITE
--WHERE FOMN.DATESTAMP = '2015-05-03'
GROUP BY 1, 2, 3, 4, 5, 6;